import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/prisma";

/**
 * GET /api/receipts/:bookingId
 *
 * Stable receipt URL (used in emails). Receipts are generated by
 * /api/bookings/:bookingId/download; this only checks ownership and redirects.
 */
export async function GET(
  request: Request,
  { params }: { params: Promise<{ bookingId: string }> },
) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { bookingId } = await params;
  const booking = await prisma.booking.findFirst({
    where: {
      OR: [{ id: bookingId }, { confirmationId: bookingId }],
      userId,
    },
    select: { id: true },
  });

  if (!booking) {
    return NextResponse.json({ error: "Booking not found" }, { status: 404 });
  }

  return NextResponse.redirect(
    new URL(`/api/bookings/${booking.id}/download`, request.url),
  );
}
