"use client";
import React, { useMemo, useEffect, useRef, useState, useCallback } from "react";
import { estimateTokens } from "@/lib/context-compression/tokens";
export { estimateTokens };
import type { Message } from "./ChatMessages";
import { playChatMessageSound, isChatSoundEnabled } from "@/lib/chatSound";

/**
 * Default context capacity in tokens for the WorkSphere AI discovery assistant.
 * Based on the model context budget directives defined for conversation pruning
 * in docs/CHATBOT_TOKEN_OPTIMIZATION.md (8k token budget).
 */
export const DEFAULT_CONTEXT_CAPACITY = 8000;

export interface ChatMessageLike {
  id?: string;
  clientMessageId?: string;
  role: "user" | "assistant" | "system" | string;
  content?: string;
  name?: string;
  status?: "pending" | "sending" | "sent" | "delivered" | "failed";
  timestamp?: number | string;
  isCompressed?: boolean;
  contextCompressed?: boolean;
  agentSteps?: Array<{
    agent: string;
    result?: Record<string, unknown>;
    compressed?: boolean;
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
}

export interface ChatTokenCounterProps {
  messages: Array<ChatMessageLike | Message>;
  input?: string;
  contextCapacity?: number;
  isCompressed?: boolean;
  showCompressionNotice?: boolean;
  className?: string;
}

export interface ChatPanelProps {
  messages?: Array<ChatMessageLike | Message>;
  input?: string;
  contextCapacity?: number;
  isCompressed?: boolean;
  onInputChange?: (value: string) => void;
  onSubmit?: (e: React.FormEvent) => void;
  children?: React.ReactNode;
  className?: string;
  onMessageDeduplicated?: (reconciledCount: number) => void;
  isReconnecting?: boolean;
  pendingMessages?: Array<ChatMessageLike | Message>;
  onReconnectSync?: () => void;
}

/**
 * Formats large token counts compactly and readably according to repository requirements:
 * 800 -> 800
 * 1200 -> 1.2k
 * 7800 -> 7.8k
 * 8000 -> 8k
 * 12000 -> 12k
 */
export function formatTokenCount(count: number): string {
  if (isNaN(count) || count <= 0) return "0";
  if (count < 1000) return String(Math.round(count));

  const thousands = count / 1000;
  const rounded = Number(thousands.toFixed(1));
  return Number.isInteger(rounded) ? `${Math.round(rounded)}k` : `${rounded}k`;
}

/**
 * Derives and clamps token usage progress (0% - 100%).
 * Prevents negative values, NaNs, or layout breaking when over capacity.
 */
export function calculateTokenProgress(
  tokens: number,
  capacity: number = DEFAULT_CONTEXT_CAPACITY,
): {
  percentage: number;
  clampedPercentage: number;
  isApproaching: boolean;
  isOverCapacity: boolean;
} {
  const safeCapacity = capacity > 0 ? capacity : DEFAULT_CONTEXT_CAPACITY;
  const safeTokens = Math.max(0, isNaN(tokens) ? 0 : tokens);
  const rawPercentage = (safeTokens / safeCapacity) * 100;
  const percentage = isNaN(rawPercentage) ? 0 : rawPercentage;
  const clampedPercentage = Math.min(100, Math.max(0, percentage));
  const isApproaching = percentage >= 80 && percentage < 100;
  const isOverCapacity = percentage >= 100;

  return {
    percentage,
    clampedPercentage,
    isApproaching,
    isOverCapacity,
  };
}

/**
 * Detects whether the active conversation has experienced context compression.
 * Checks for:
 * 1. Explicit boolean flag (`isCompressed` / `contextCompressed`)
 * 2. System messages generated by `compressContext` containing `[PRIOR CONTEXT & PARAMETERS]`
 * 3. Message metadata indicating compression from API route
 */
export function checkIsContextCompressed(
  messages: Array<ChatMessageLike | Message> = [],
  explicitIsCompressed?: boolean,
): boolean {
  if (explicitIsCompressed) return true;
  if (!Array.isArray(messages) || messages.length === 0) return false;

  return messages.some((raw) => {
    if (!raw) return false;
    const m = raw as any;
    if (m.isCompressed === true || m.contextCompressed === true) return true;
    if (m.role === "system" && typeof m.content === "string") {
      return (
        m.content.startsWith("[PRIOR CONTEXT & PARAMETERS]") ||
        m.content.includes("Prior Context:")
      );
    }
    if (Array.isArray(m.agentSteps)) {
      return m.agentSteps.some(
        (step: any) =>
          step?.agent === "Compression" ||
          step?.compressed === true ||
          (step?.result as Record<string, unknown>)?.compressed === true,
      );
    }
    return false;
  });
}

/**
 * Hook to compute memoized token estimates and progress metrics.
 * Separates historical conversation token estimation from active draft input
 * to maintain 60fps responsive typing performance without repeated retokenization.
 */
export function useChatTokens(
  messages: Array<ChatMessageLike | Message> = [],
  input: string = "",
  contextCapacity: number = DEFAULT_CONTEXT_CAPACITY,
) {
  const historyTokens = useMemo(() => {
    if (!Array.isArray(messages)) return 0;
    return messages.reduce((acc, m) => {
      if (!m) return acc;
      const text = typeof m === "string" ? m : m.content || "";
      return acc + (text ? estimateTokens(text) : 0);
    }, 0);
  }, [messages]);

  const draftTokens = useMemo(() => {
    if (!input || typeof input !== "string") return 0;
    return estimateTokens(input);
  }, [input]);

  const totalTokens = historyTokens + draftTokens;

  const progress = useMemo(
    () => calculateTokenProgress(totalTokens, contextCapacity),
    [totalTokens, contextCapacity],
  );

  return {
    historyTokens,
    draftTokens,
    totalTokens,
    formattedUsage: formatTokenCount(totalTokens),
    formattedCapacity: formatTokenCount(contextCapacity),
    ...progress,
  };
}

/**
 * Inline divider notice displayed when earlier messages have been compressed.
 */
export function CompressionNotice({ className }: { className?: string }) {
  return (
    <div
      role="status"
      aria-live="polite"
      data-testid="compression-notice"
      className={`my-3 flex items-center justify-center gap-2 text-xs text-zinc-500 dark:text-zinc-400 select-none ${
        className || ""
      }`}
    >
      <div className="h-px flex-1 bg-zinc-200 dark:bg-zinc-700" />
      <span className="px-2 font-medium">
        Earlier messages compressed to preserve memory
      </span>
      <div className="h-px flex-1 bg-zinc-200 dark:bg-zinc-700" />
    </div>
  );
}

/**
 * Subtle footer token counter and capacity progress indicator.
 */
export function ChatTokenCounter({
  messages = [],
  input = "",
  contextCapacity = DEFAULT_CONTEXT_CAPACITY,
  isCompressed,
  showCompressionNotice = true,
  className,
}: ChatTokenCounterProps) {
  const {
    totalTokens,
    formattedUsage,
    formattedCapacity,
    clampedPercentage,
    isApproaching,
    isOverCapacity,
  } = useChatTokens(messages, input, contextCapacity);

  const isCompressedState = useMemo(
    () => checkIsContextCompressed(messages, isCompressed),
    [messages, isCompressed],
  );

  let progressBarColor = "bg-blue-500 dark:bg-blue-400";
  if (isOverCapacity) {
    progressBarColor = "bg-red-500 dark:bg-red-400";
  } else if (isApproaching) {
    progressBarColor = "bg-amber-500 dark:bg-amber-400";
  }

  return (
    <div
      data-testid="chat-token-counter"
      data-tokens={totalTokens}
      className={`w-full flex flex-col gap-1.5 px-4 py-2 border-t border-zinc-200 dark:border-zinc-800 bg-zinc-50/80 dark:bg-zinc-900/60 transition-colors ${
        className || ""
      }`}
    >
      {showCompressionNotice && isCompressedState && <CompressionNotice />}

      <div className="flex items-center justify-between text-xs text-zinc-600 dark:text-zinc-400 font-medium">
        <span>
          Context: {formattedUsage} / {formattedCapacity} tokens
        </span>
        {isOverCapacity ? (
          <span className="text-[10px] font-semibold text-red-600 dark:text-red-400">
            Context limit exceeded
          </span>
        ) : isApproaching ? (
          <span className="text-[10px] font-semibold text-amber-600 dark:text-amber-400">
            Approaching limit
          </span>
        ) : null}
      </div>

      <div
        role="progressbar"
        aria-label="Context window token usage"
        aria-valuenow={Math.round(clampedPercentage)}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-valuetext={`Context: ${formattedUsage} / ${formattedCapacity} tokens (${Math.round(
          clampedPercentage,
        )}%)`}
        className="h-1.5 w-full overflow-hidden rounded-full bg-zinc-200 dark:bg-zinc-700/60"
      >
        <div
          data-testid="token-progress-bar"
          className={`h-full transition-all duration-300 ease-out ${progressBarColor}`}
          style={{ width: `${clampedPercentage}%` }}
        />
      </div>
    </div>
  );
}

/**
 * Generates a deterministic clientMessageId deduplication key for optimistic chat messages.
 * Uses role, content snippet, and timestamp to ensure uniqueness across connections.
 */
export function generateClientMessageId(
  content: string = "",
  role: string = "user",
  timestamp: number = Date.now()
): string {
  const cleanContent = content.trim().replace(/\s+/g, "_").slice(0, 32);
  const hash = Math.abs(
    cleanContent.split("").reduce((acc, char) => (acc << 5) - acc + char.charCodeAt(0), 0)
  ).toString(36);
  return `cmid_${role}_${timestamp.toString(36)}_${hash}`;
}

/**
 * Creates a structured optimistic ChatMessageLike object with a deterministic clientMessageId key.
 */
export function createOptimisticMessage(
  content: string,
  role: "user" | "assistant" | "system" = "user",
  clientMessageId?: string
): ChatMessageLike {
  const ts = Date.now();
  return {
    clientMessageId: clientMessageId || generateClientMessageId(content, role, ts),
    role,
    content,
    status: "pending",
    timestamp: ts,
  };
}

/**
 * Deduplicates and reconciles an incoming list of chat messages against an existing message list.
 * Key features:
 * 1. Matches incoming messages with local pending/optimistic messages via `clientMessageId`.
 * 2. Reconciles server confirmation (`id`, `status="sent"`) into existing optimistic entries without duplication.
 * 3. Fallback signature matching (role + content) for socket reconnect replay of un-keyed local messages.
 * 4. Preserves order and prevents duplicated rendering on fast WebSocket / PartySocket reconnects.
 */
export function deduplicateMessages<T extends ChatMessageLike>(
  existingMessages: T[] = [],
  incomingMessages: T[] = []
): { deduplicated: T[]; reconciledCount: number } {
  if (!Array.isArray(incomingMessages) || incomingMessages.length === 0) {
    return { deduplicated: [...existingMessages], reconciledCount: 0 };
  }
  if (!Array.isArray(existingMessages) || existingMessages.length === 0) {
    const seen = new Set<string>();
    const deduplicatedIncoming: T[] = [];
    for (const msg of incomingMessages) {
      if (!msg) continue;
      const key = msg.clientMessageId || msg.id || `${msg.role}:${msg.content}`;
      if (!seen.has(key)) {
        seen.add(key);
        deduplicatedIncoming.push(msg);
      }
    }
    return { deduplicated: deduplicatedIncoming, reconciledCount: 0 };
  }

  const result: T[] = [...existingMessages];
  let reconciledCount = 0;

  const clientMessageIdMap = new Map<string, number>();
  const idMap = new Map<string, number>();
  const signatureMap = new Map<string, number>();

  result.forEach((msg, idx) => {
    if (!msg) return;
    if (msg.clientMessageId) {
      clientMessageIdMap.set(msg.clientMessageId, idx);
    }
    if (msg.id) {
      idMap.set(msg.id, idx);
    }
    if (msg.role && typeof msg.content === "string") {
      const sig = `${msg.role}:${msg.content.trim()}`;
      if (!signatureMap.has(sig) || msg.status === "pending") {
        signatureMap.set(sig, idx);
      }
    }
  });

  for (const incoming of incomingMessages) {
    if (!incoming) continue;

    // 1. Match by explicit clientMessageId
    if (incoming.clientMessageId && clientMessageIdMap.has(incoming.clientMessageId)) {
      const idx = clientMessageIdMap.get(incoming.clientMessageId)!;
      result[idx] = {
        ...result[idx],
        ...incoming,
        status: incoming.status || "sent",
        clientMessageId: incoming.clientMessageId || result[idx].clientMessageId,
      };
      reconciledCount++;
      continue;
    }

    // 2. Match by server ID
    if (incoming.id && idMap.has(incoming.id)) {
      const idx = idMap.get(incoming.id)!;
      result[idx] = {
        ...result[idx],
        ...incoming,
        status: incoming.status || "sent",
      };
      reconciledCount++;
      continue;
    }

    // 3. Fallback: match optimistic pending message with matching content and role
    if (incoming.role && typeof incoming.content === "string") {
      const sig = `${incoming.role}:${incoming.content.trim()}`;
      if (signatureMap.has(sig)) {
        const idx = signatureMap.get(sig)!;
        const existingMsg = result[idx];
        if (existingMsg.status === "pending" || !existingMsg.id) {
          result[idx] = {
            ...existingMsg,
            ...incoming,
            status: incoming.status || "sent",
            clientMessageId: existingMsg.clientMessageId || incoming.clientMessageId,
          };
          reconciledCount++;
          signatureMap.delete(sig);
          continue;
        }
      }
    }

    // 4. Not matched: new unique incoming message, append to list
    const newIdx = result.length;
    result.push(incoming);

    if (incoming.clientMessageId) {
      clientMessageIdMap.set(incoming.clientMessageId, newIdx);
    }
    if (incoming.id) {
      idMap.set(incoming.id, newIdx);
    }
    if (incoming.role && typeof incoming.content === "string") {
      signatureMap.set(`${incoming.role}:${incoming.content.trim()}`, newIdx);
    }
  }

  return { deduplicated: result, reconciledCount };
}

/**
 * Reconciles incoming message(s) against existing message state.
 * Useful for single socket broadcasts or batch reconnect sync events.
 */
export function reconcileMessageState<T extends ChatMessageLike>(
  currentMessages: T[] = [],
  incoming: T | T[],
  options: { isReconnect?: boolean } = {}
): T[] {
  const incomingArray = Array.isArray(incoming) ? incoming : [incoming];
  const { deduplicated } = deduplicateMessages(currentMessages, incomingArray);
  return deduplicated;
}

/**
 * Hook to manage chat message state with built-in clientMessageId deduplication,
 * optimistic message queueing, and PartySocket fast reconnect reconciliation.
 */
export function useDeduplicatedMessages<T extends ChatMessageLike = ChatMessageLike>(
  initialMessages: T[] = []
) {
  const [messages, setMessages] = useState<T[]>(() => {
    return deduplicateMessages([], initialMessages).deduplicated;
  });

  const addOptimisticMessage = useCallback(
    (msg: Omit<T, "clientMessageId"> & { clientMessageId?: string }): T => {
      const clientMessageId =
        msg.clientMessageId || generateClientMessageId(msg.content || "", msg.role || "user");
      const optimistic = {
        ...msg,
        clientMessageId,
        status: msg.status || "pending",
        timestamp: msg.timestamp || Date.now(),
      } as T;

      setMessages((prev) => {
        const { deduplicated } = deduplicateMessages(prev, [optimistic]);
        return deduplicated;
      });

      return optimistic;
    },
    []
  );

  const reconcileIncoming = useCallback(
    (incoming: T | T[], isReconnect: boolean = false) => {
      setMessages((prev) => reconcileMessageState(prev, incoming, { isReconnect }));
    },
    []
  );

  const confirmMessage = useCallback((clientMessageId: string, serverId?: string) => {
    setMessages((prev) =>
      prev.map((m) =>
        m.clientMessageId === clientMessageId
          ? { ...m, id: serverId || m.id, status: "sent" }
          : m
      )
    );
  }, []);

  const pendingCount = useMemo(
    () => messages.filter((m) => m.status === "pending" || m.status === "sending").length,
    [messages]
  );

  return {
    messages,
    setMessages,
    addOptimisticMessage,
    reconcileIncoming,
    confirmMessage,
    pendingCount,
  };
}

/**
 * Custom hook for PartySocket / WebSocket reconnect deduplication management.
 * Tracks reconnect events and prevents already rendered optimistic messages
 * from being duplicated when receiving server sync broadcasts.
 */
export function useChatReconnectDeduplication<T extends ChatMessageLike = ChatMessageLike>(
  messages: T[],
  onSyncComplete?: (count: number) => void
) {
  const [isReconnecting, setIsReconnecting] = useState(false);
  const pendingBufferRef = useRef<Map<string, T>>(new Map());

  const handleBeforeReconnect = useCallback(() => {
    setIsReconnecting(true);
    messages.forEach((m) => {
      if ((m.status === "pending" || m.status === "sending") && m.clientMessageId) {
        pendingBufferRef.current.set(m.clientMessageId, m);
      }
    });
  }, [messages]);

  const handleReconnectSync = useCallback(
    (incomingServerMessages: T[]) => {
      const { deduplicated, reconciledCount } = deduplicateMessages(
        messages,
        incomingServerMessages
      );
      setIsReconnecting(false);
      pendingBufferRef.current.clear();
      onSyncComplete?.(reconciledCount);
      return deduplicated;
    },
    [messages, onSyncComplete]
  );

  return {
    isReconnecting,
    handleBeforeReconnect,
    handleReconnectSync,
  };
}

/**
 * Main ChatPanel component representing the chat interface with message display,
 * compression notices, and token capacity footer.
 */
export function ChatPanel({
  messages = [],
  input = "",
  contextCapacity = DEFAULT_CONTEXT_CAPACITY,
  isCompressed,
  onInputChange,
  onSubmit,
  children,
  className,
  onMessageDeduplicated,
  isReconnecting,
  pendingMessages,
  onReconnectSync,
}: ChatPanelProps) {
  const combinedMessages = useMemo(() => {
    const all = [...messages, ...(pendingMessages || [])];
    const { deduplicated, reconciledCount } = deduplicateMessages([], all);
    if (reconciledCount > 0 && onMessageDeduplicated) {
      onMessageDeduplicated(reconciledCount);
    }
    return deduplicated;
  }, [messages, pendingMessages, onMessageDeduplicated]);

  const isCompressedState = useMemo(
    () => checkIsContextCompressed(combinedMessages, isCompressed),
    [combinedMessages, isCompressed]
  );

  const prevMessageCountRef = useRef(combinedMessages.length);

  useEffect(() => {
    if (combinedMessages.length > prevMessageCountRef.current) {
      const lastMsg = combinedMessages[combinedMessages.length - 1];
      if (lastMsg?.role === "assistant") {
        playChatMessageSound();
      }
    }
    prevMessageCountRef.current = combinedMessages.length;
  }, [combinedMessages]);

  return (
    <div
      data-testid="chat-panel"
      className={`flex flex-col h-full w-full bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl overflow-hidden shadow-sm ${
        className || ""
      }`}
    >
      {isReconnecting && (
        <div
          data-testid="reconnecting-banner"
          aria-live="polite"
          className="bg-amber-50 dark:bg-amber-950/40 border-b border-amber-200 dark:border-amber-800 px-4 py-1.5 text-xs text-amber-800 dark:text-amber-300 flex items-center justify-between"
        >
          <span>Reconnecting to chat room... Synchronizing messages.</span>
          {onReconnectSync && (
            <button
              onClick={onReconnectSync}
              className="underline font-medium hover:text-amber-900 dark:hover:text-amber-100"
            >
              Sync now
            </button>
          )}
        </div>
      )}

      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {isCompressedState && <CompressionNotice />}
        {children}
        {!children && combinedMessages.length === 0 && (
          <div className="text-center py-8 text-zinc-400 text-sm">
            No messages yet.
          </div>
        )}
        {!children &&
          combinedMessages.map((m, idx) => {
            const messageKey = m.clientMessageId || m.id || `msg-${idx}`;
            const isPending = m.status === "pending" || m.status === "sending";
            return (
              <div
                key={messageKey}
                data-testid={`chat-message-${m.id || m.clientMessageId || idx}`}
                data-client-message-id={m.clientMessageId}
                className={`flex ${
                  m.role === "user" ? "justify-end" : "justify-start"
                }`}
              >
                <div
                  className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-sm relative transition-opacity ${
                    m.role === "user"
                      ? "bg-zinc-950 dark:bg-zinc-100 text-white dark:text-zinc-900"
                      : "bg-zinc-100 dark:bg-zinc-800 text-zinc-900 dark:text-white"
                  } ${isPending ? "opacity-75" : "opacity-100"}`}
                >
                  {m.content}
                  {isPending && (
                    <span
                      data-testid="pending-indicator"
                      className="ml-2 text-[10px] opacity-60 inline-block font-mono"
                    >
                      (sending...)
                    </span>
                  )}
                </div>
              </div>
            );
          })}
      </div>

      {onSubmit && (
        <form
          onSubmit={onSubmit}
          className="p-3 border-t border-zinc-200 dark:border-zinc-800 flex gap-2"
        >
          <input
            type="text"
            value={input}
            onChange={(e) => onInputChange?.(e.target.value)}
            placeholder="Type a message..."
            className="flex-1 px-3 py-1.5 text-sm rounded-lg border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-zinc-100"
          />
          <button
            type="submit"
            className="px-3 py-1.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            Send
          </button>
        </form>
      )}

      <ChatTokenCounter
        messages={combinedMessages}
        input={input}
        contextCapacity={contextCapacity}
        isCompressed={isCompressed}
        showCompressionNotice={false}
      />
    </div>
  );
}

export default ChatPanel;
