"use client";
import React, { useMemo, useEffect, useRef } from "react";
import { estimateTokens } from "@/lib/context-compression/tokens";
export { estimateTokens };
import type { Message } from "./ChatMessages";
import { playChatMessageSound, isChatSoundEnabled } from "@/lib/chatSound";

/**
 * Default context capacity in tokens for the WorkSphere AI discovery assistant.
 * Based on the model context budget directives defined for conversation pruning
 * in docs/CHATBOT_TOKEN_OPTIMIZATION.md (8k token budget).
 */
export const DEFAULT_CONTEXT_CAPACITY = 8000;

export interface ChatMessageLike {
  id?: string;
  role: "user" | "assistant" | "system" | string;
  content?: string;
  name?: string;
  isCompressed?: boolean;
  contextCompressed?: boolean;
  agentSteps?: Array<{
    agent: string;
    result?: Record<string, unknown>;
    compressed?: boolean;
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
}

export interface ChatTokenCounterProps {
  messages: Array<ChatMessageLike | Message>;
  input?: string;
  contextCapacity?: number;
  isCompressed?: boolean;
  showCompressionNotice?: boolean;
  className?: string;
}

export interface ChatPanelProps {
  messages?: Array<ChatMessageLike | Message>;
  input?: string;
  contextCapacity?: number;
  isCompressed?: boolean;
  onInputChange?: (value: string) => void;
  onSubmit?: (e: React.FormEvent) => void;
  children?: React.ReactNode;
  className?: string;
}

/**
 * Formats large token counts compactly and readably according to repository requirements:
 * 800 -> 800
 * 1200 -> 1.2k
 * 7800 -> 7.8k
 * 8000 -> 8k
 * 12000 -> 12k
 */
export function formatTokenCount(count: number): string {
  if (isNaN(count) || count <= 0) return "0";
  if (count < 1000) return String(Math.round(count));

  const thousands = count / 1000;
  const rounded = Number(thousands.toFixed(1));
  return Number.isInteger(rounded) ? `${Math.round(rounded)}k` : `${rounded}k`;
}

/**
 * Derives and clamps token usage progress (0% - 100%).
 * Prevents negative values, NaNs, or layout breaking when over capacity.
 */
export function calculateTokenProgress(
  tokens: number,
  capacity: number = DEFAULT_CONTEXT_CAPACITY,
): {
  percentage: number;
  clampedPercentage: number;
  isApproaching: boolean;
  isOverCapacity: boolean;
} {
  const safeCapacity = capacity > 0 ? capacity : DEFAULT_CONTEXT_CAPACITY;
  const safeTokens = Math.max(0, isNaN(tokens) ? 0 : tokens);
  const rawPercentage = (safeTokens / safeCapacity) * 100;
  const percentage = isNaN(rawPercentage) ? 0 : rawPercentage;
  const clampedPercentage = Math.min(100, Math.max(0, percentage));
  const isApproaching = percentage >= 80 && percentage < 100;
  const isOverCapacity = percentage >= 100;

  return {
    percentage,
    clampedPercentage,
    isApproaching,
    isOverCapacity,
  };
}

/**
 * Detects whether the active conversation has experienced context compression.
 * Checks for:
 * 1. Explicit boolean flag (`isCompressed` / `contextCompressed`)
 * 2. System messages generated by `compressContext` containing `[PRIOR CONTEXT & PARAMETERS]`
 * 3. Message metadata indicating compression from API route
 */
export function checkIsContextCompressed(
  messages: Array<ChatMessageLike | Message> = [],
  explicitIsCompressed?: boolean,
): boolean {
  if (explicitIsCompressed) return true;
  if (!Array.isArray(messages) || messages.length === 0) return false;

  return messages.some((raw) => {
    if (!raw) return false;
    const m = raw as any;
    if (m.isCompressed === true || m.contextCompressed === true) return true;
    if (m.role === "system" && typeof m.content === "string") {
      return (
        m.content.startsWith("[PRIOR CONTEXT & PARAMETERS]") ||
        m.content.includes("Prior Context:")
      );
    }
    if (Array.isArray(m.agentSteps)) {
      return m.agentSteps.some(
        (step: any) =>
          step?.agent === "Compression" ||
          step?.compressed === true ||
          (step?.result as Record<string, unknown>)?.compressed === true,
      );
    }
    return false;
  });
}

/**
 * Hook to compute memoized token estimates and progress metrics.
 * Separates historical conversation token estimation from active draft input
 * to maintain 60fps responsive typing performance without repeated retokenization.
 */
export function useChatTokens(
  messages: Array<ChatMessageLike | Message> = [],
  input: string = "",
  contextCapacity: number = DEFAULT_CONTEXT_CAPACITY,
) {
  const historyTokens = useMemo(() => {
    if (!Array.isArray(messages)) return 0;
    return messages.reduce((acc, m) => {
      if (!m) return acc;
      const text = typeof m === "string" ? m : m.content || "";
      return acc + (text ? estimateTokens(text) : 0);
    }, 0);
  }, [messages]);

  const draftTokens = useMemo(() => {
    if (!input || typeof input !== "string") return 0;
    return estimateTokens(input);
  }, [input]);

  const totalTokens = historyTokens + draftTokens;

  const progress = useMemo(
    () => calculateTokenProgress(totalTokens, contextCapacity),
    [totalTokens, contextCapacity],
  );

  return {
    historyTokens,
    draftTokens,
    totalTokens,
    formattedUsage: formatTokenCount(totalTokens),
    formattedCapacity: formatTokenCount(contextCapacity),
    ...progress,
  };
}

/**
 * Inline divider notice displayed when earlier messages have been compressed.
 */
export function CompressionNotice({ className }: { className?: string }) {
  return (
    <div
      role="status"
      aria-live="polite"
      data-testid="compression-notice"
      className={`my-3 flex items-center justify-center gap-2 text-xs text-zinc-500 dark:text-zinc-400 select-none ${
        className || ""
      }`}
    >
      <div className="h-px flex-1 bg-zinc-200 dark:bg-zinc-700" />
      <span className="px-2 font-medium">
        Earlier messages compressed to preserve memory
      </span>
      <div className="h-px flex-1 bg-zinc-200 dark:bg-zinc-700" />
    </div>
  );
}

/**
 * Subtle footer token counter and capacity progress indicator.
 */
export function ChatTokenCounter({
  messages = [],
  input = "",
  contextCapacity = DEFAULT_CONTEXT_CAPACITY,
  isCompressed,
  showCompressionNotice = true,
  className,
}: ChatTokenCounterProps) {
  const {
    totalTokens,
    formattedUsage,
    formattedCapacity,
    clampedPercentage,
    isApproaching,
    isOverCapacity,
  } = useChatTokens(messages, input, contextCapacity);

  const isCompressedState = useMemo(
    () => checkIsContextCompressed(messages, isCompressed),
    [messages, isCompressed],
  );

  let progressBarColor = "bg-blue-500 dark:bg-blue-400";
  if (isOverCapacity) {
    progressBarColor = "bg-red-500 dark:bg-red-400";
  } else if (isApproaching) {
    progressBarColor = "bg-amber-500 dark:bg-amber-400";
  }

  return (
    <div
      data-testid="chat-token-counter"
      data-tokens={totalTokens}
      className={`w-full flex flex-col gap-1.5 px-4 py-2 border-t border-zinc-200 dark:border-zinc-800 bg-zinc-50/80 dark:bg-zinc-900/60 transition-colors ${
        className || ""
      }`}
    >
      {showCompressionNotice && isCompressedState && <CompressionNotice />}

      <div className="flex items-center justify-between text-xs text-zinc-600 dark:text-zinc-400 font-medium">
        <span>
          Context: {formattedUsage} / {formattedCapacity} tokens
        </span>
        {isOverCapacity ? (
          <span className="text-[10px] font-semibold text-red-600 dark:text-red-400">
            Context limit exceeded
          </span>
        ) : isApproaching ? (
          <span className="text-[10px] font-semibold text-amber-600 dark:text-amber-400">
            Approaching limit
          </span>
        ) : null}
      </div>

      <div
        role="progressbar"
        aria-label="Context window token usage"
        aria-valuenow={Math.round(clampedPercentage)}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-valuetext={`Context: ${formattedUsage} / ${formattedCapacity} tokens (${Math.round(
          clampedPercentage,
        )}%)`}
        className="h-1.5 w-full overflow-hidden rounded-full bg-zinc-200 dark:bg-zinc-700/60"
      >
        <div
          data-testid="token-progress-bar"
          className={`h-full transition-all duration-300 ease-out ${progressBarColor}`}
          style={{ width: `${clampedPercentage}%` }}
        />
      </div>
    </div>
  );
}

/**
 * Main ChatPanel component representing the chat interface with message display,
 * compression notices, and token capacity footer.
 */
export function ChatPanel({
  messages = [],
  input = "",
  contextCapacity = DEFAULT_CONTEXT_CAPACITY,
  isCompressed,
  onInputChange,
  onSubmit,
  children,
  className,
}: ChatPanelProps) {
  const isCompressedState = useMemo(
    () => checkIsContextCompressed(messages, isCompressed),
    [messages, isCompressed],
  );

  const prevMessageCountRef = useRef(messages.length);

  useEffect(() => {
    // When a new message arrives, chime only for incoming assistant replies
    if (messages.length > prevMessageCountRef.current) {
      const lastMsg = messages[messages.length - 1];
      if (lastMsg?.role === "assistant") {
        playChatMessageSound();
      }
    }
    prevMessageCountRef.current = messages.length;
  }, [messages]);

  return (
    <div
      data-testid="chat-panel"
      className={`flex flex-col h-full w-full bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl overflow-hidden shadow-sm ${
        className || ""
      }`}
    >
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {isCompressedState && <CompressionNotice />}
        {children}
        {!children && messages.length === 0 && (
          <div className="text-center py-8 text-zinc-400 text-sm">
            No messages yet.
          </div>
        )}
        {!children &&
          messages.map((m, idx) => (
            <div
              key={m.id || `msg-${idx}`}
              className={`flex ${
                m.role === "user" ? "justify-end" : "justify-start"
              }`}
            >
              <div
                className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-sm ${
                  m.role === "user"
                    ? "bg-zinc-950 dark:bg-zinc-100 text-white dark:text-zinc-900"
                    : "bg-zinc-100 dark:bg-zinc-800 text-zinc-900 dark:text-white"
                }`}
              >
                {m.content}
              </div>
            </div>
          ))}
      </div>

      {onSubmit && (
        <form
          onSubmit={onSubmit}
          className="p-3 border-t border-zinc-200 dark:border-zinc-800 flex gap-2"
        >
          <input
            type="text"
            value={input}
            onChange={(e) => onInputChange?.(e.target.value)}
            placeholder="Type a message..."
            className="flex-1 px-3 py-1.5 text-sm rounded-lg border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-zinc-100"
          />
          <button
            type="submit"
            className="px-3 py-1.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            Send
          </button>
        </form>
      )}

      <ChatTokenCounter
        messages={messages}
        input={input}
        contextCapacity={contextCapacity}
        isCompressed={isCompressed}
        showCompressionNotice={false}
      />
    </div>
  );
}

export default ChatPanel;
